<a href="https://colab.research.google.com/github/qa21336/HousingStatisticsAnalysis-/blob/main/populationDataWrangling_mountDrive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ADS Data Wrangling for Population Dataset

### Explore the dataset

In [8]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

popDf = pd.read_csv("/content/drive/MyDrive/ADS Datasets/MYEB1_detailed_population_estimates_series_UK_(2020_geog21).csv")

# We dont need Local Area name as well as code
popDf = popDf.drop("laname21", axis=1)
popDf.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,ladcode21,country,sex,age,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,...,population_2011,population_2012,population_2013,population_2014,population_2015,population_2016,population_2017,population_2018,population_2019,population_2020
0,E06000001,E,1,0,525,502,516,553,531,583,...,601,595,576,551,497,576,507,535,515,517
1,E06000001,E,1,1,544,526,498,526,550,539,...,573,615,601,567,553,512,570,515,532,519
2,E06000001,E,1,2,548,548,551,507,521,539,...,580,586,621,600,576,562,534,576,515,528
3,E06000001,E,1,3,556,546,548,553,508,514,...,600,578,584,625,598,579,565,530,583,520
4,E06000001,E,1,4,606,549,553,540,554,512,...,600,616,593,568,620,604,591,576,533,580

In [9]:
import numpy as np

# Find age range for restructured data
print("youngest age is: "+str(np.min(popDf.loc[:, "age"].to_numpy())))
print("oldest age is: "+str(np.max(popDf.loc[:, "age"].to_numpy())))

youngest age is: 0
oldest age is: 90

### Extract important information from columns and create place for restructured data

In [11]:
# Get countries
countries = np.unique(popDf.loc[:, "country"].to_numpy())

# Get population columns and years
population_cols = list(filter(lambda s: s[0] == "p", popDf.columns))
years = list(map(lambda col: col.split("_")[1], population_cols))

# Create place for restructured data
newPopDict = {}
newPopDict["country"] = []
newPopDict["year"] = []
newPopDict["population"] = []

for i in range(0, 100, 10):
    colName = "age_"+str(i)+"-"+str(i+10)+"_proportion"
    newPopDict[colName] = []

print(newPopDict)

{'country': [], 'year': [], 'population': [], 'age_0-10_proportion': [], 'age_10-20_proportion': [], 'age_20-30_proportion': [], 'age_30-40_proportion': [], 'age_40-50_proportion': [], 'age_50-60_proportion': [], 'age_60-70_proportion': [], 'age_70-80_proportion': [], 'age_80-90_proportion': [], 'age_90-100_proportion': []}

### Fill in Population Sums

In [12]:
# Extract sum of populations in each year
for country in countries:
    rowsForCountry = popDf.loc[popDf["country"] == country]

    # Get sum for each year
    for year, popCol in zip(years, population_cols):
        sum = np.sum(rowsForCountry.loc[:, popCol].to_numpy())

        # Update newPopDf
        newPopDict["country"].append(country)
        newPopDict["year"].append(year)
        newPopDict["population"].append(sum)

### Fill in Age Ratios

In [13]:
# Extract proportion of population in each decade of their lives
for country in newPopDict["country"]:
    rowsForCountry = popDf.loc[popDf["country"] == country]

    # Get proportion for each year
    for year, popCol in zip(years, population_cols):
        cellsForCountryYear = rowsForCountry.loc[:, ["age", popCol]].to_numpy()

        # Get Ages
        for age in range(0, 100, 10):
            # Get every row in the age band (for right country / year)
            agePopsInRange = np.array(list(filter(lambda agePop: age <= agePop[0] and agePop[0] < age + 10,
                                                  cellsForCountryYear)))

            # Log the population sum
            newPopDict["age_"+str(age)+"-"+str(age+10)+"_proportion"] = np.sum(agePopsInRange, axis=0)[1]

In [14]:
newPopDf = pd.DataFrame(data=newPopDict)
newPopDf

,country,year,population,age_0-10_proportion,age_10-20_proportion,age_20-30_proportion,age_30-40_proportion,age_40-50_proportion,age_50-60_proportion,age_60-70_proportion,age_70-80_proportion,age_80-90_proportion,age_90-100_proportion
0,E,2001,49449746,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
1,E,2002,49679267,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
2,E,2003,49925517,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
3,E,2004,50194600,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
4,E,2005,50606034,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,W,2016,3113150,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
76,W,2017,3125165,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
77,W,2018,3138631,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
78,W,2019,3152879,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760
79,W,2020,3169586,343519,358258,414671,382545,365395,439192,377371,312909,144966,30760